<script setup lang="ts">
import { formatSettlementAmountMinor } from '../../../../domain/settlement'
const route = useRoute(); const groupsStore = useGroupsStore()
const groupId = computed(() => String(route.params.id)); const group = computed(() => groupsStore.findGroup(groupId.value))
const settlements = computed(() => groupsStore.settlementsForGroup(groupId.value))
const participantNames = computed(() => new Map(groupsStore.participantsForGroup(groupId.value).map(item => [item.id, item.name])))
</script>

<template><main class="page-shell"><div v-if="group" class="page-content"><NuxtLink to="/" class="secondary-link -ml-4 mb-3">← Gruppen</NuxtLink><header><p class="text-sm font-semibold tracking-wide text-brand-700">{{ group.name }}</p><h1 class="mt-2 text-3xl font-semibold text-brand-900">Zahlungen</h1><p class="mt-2 text-gray-600">Tatsächlich erfolgte Ausgleichszahlungen.</p></header><GroupAreaNavigation :group-id="group.id" /><GroupSyncStatus :group-id="group.id" class="mt-6" /><p v-if="route.query.deleted === '1'" class="mt-4 rounded-lg bg-brand-50 p-3 text-brand-900" role="status">Zahlung lokal gelöscht.</p><p v-if="!settlements.length" class="card mt-6 p-5 text-center">Noch keine Zahlungen erfasst.</p><ul v-else class="mt-6 space-y-3"><li v-for="settlement in settlements" :key="settlement.id"><NuxtLink :to="`/groups/${group.id}/settlements/${settlement.id}`" class="card block p-4"><span class="flex justify-between gap-4"><strong>{{ participantNames.get(settlement.senderParticipantId) }} → {{ participantNames.get(settlement.receiverParticipantId) }}</strong><span>{{ formatSettlementAmountMinor(settlement.amountMinor) }}</span></span><span class="mt-1 block text-sm text-gray-600">{{ settlement.occurredOn }}</span></NuxtLink></li></ul><NuxtLink v-if="group.status === 'active'" :to="`/groups/${group.id}/settlements/new`" class="primary-button mt-5 w-full">Zahlung erfassen</NuxtLink><p v-else class="card mt-5 p-4">Diese archivierte Gruppe ist schreibgeschützt.</p></div><div v-else class="page-content"><h1 class="text-3xl font-semibold">Gruppe nicht gefunden</h1></div></main></template>
