<script setup lang="ts">
import { formatAmountMinor } from '../../../../domain/expense'
const route = useRoute(); const router = useRouter(); const groupsStore = useGroupsStore(); const { remove } = useExpenses()
const groupId = computed(() => String(route.params.id)); const expenseId = computed(() => String(route.params.expenseId)); const group = computed(() => groupsStore.findGroup(groupId.value)); const expense = computed(() => groupsStore.expenses.find(item => item.id === expenseId.value && item.groupId === groupId.value)); const participants = computed(() => new Map(groupsStore.participantsForGroup(groupId.value).map(item => [item.id, item])))
const editing = ref(false); const dialog = ref<HTMLDialogElement | null>(null); const deleteButton = ref<HTMLButtonElement | null>(null); const deleteTrigger = ref<HTMLButtonElement | null>(null); const status = ref('')
function saved() { editing.value = false; status.value = 'Änderungen wurden lokal gespeichert.' }
function askDelete() { dialog.value?.showModal(); nextTick(() => deleteButton.value?.focus()) }
function cancelDelete() { dialog.value?.close(); nextTick(() => deleteTrigger.value?.focus()) }
async function confirmDelete() { if (!expense.value) return; try { await remove(expense.value); dialog.value?.close(); await router.push(`/groups/${groupId.value}?deleted=1`) } catch { status.value = 'Die Ausgabe konnte nicht lokal gelöscht werden.'; dialog.value?.close() } }
</script>
<template><main class="page-shell"><div v-if="group && expense" class="page-content"><NuxtLink :to="`/groups/${group.id}`" class="secondary-link -ml-4 mb-3">← Ausgaben</NuxtLink><header><p class="text-sm font-semibold tracking-wide text-brand-700">{{ group.name }}</p><h1 class="mt-2 text-3xl font-semibold text-brand-900">{{ expense.description }}</h1></header><p v-if="route.query.created === '1'" class="mt-5 rounded-lg bg-brand-50 p-3 text-brand-900" role="status">Ausgabe lokal gespeichert.</p><GroupSyncStatus :group-id="group.id" class="mt-4" /><p v-if="status" class="mt-4" :role="status.includes('konnte nicht') ? 'alert' : 'status'">{{ status }}</p><ExpenseForm v-if="editing" class="mt-6" :group-id="group.id" :expense="expense" @saved="saved" /><template v-else><dl class="card mt-6 grid grid-cols-1 gap-4 p-5 sm:grid-cols-2"><div><dt class="text-sm text-gray-600">Betrag</dt><dd class="font-semibold">{{ formatAmountMinor(expense.amountMinor) }}</dd></div><div><dt class="text-sm text-gray-600">Datum</dt><dd class="font-semibold">{{ expense.incurredOn }}</dd></div><div class="sm:col-span-2"><dt class="text-sm text-gray-600">Bezahlt von</dt><dd class="font-semibold">{{ participants.get(expense.payerParticipantId)?.name }}</dd></div></dl><section class="card mt-5 p-5" aria-labelledby="shares-title"><h2 id="shares-title" class="text-xl font-semibold">Aufteilung</h2><ul class="mt-3 space-y-2"><li v-for="share in expense.shares" :key="share.participantId" class="flex justify-between gap-4"><span>{{ participants.get(share.participantId)?.name }}</span><strong>{{ formatAmountMinor(share.amountMinor) }}</strong></li></ul></section><div v-if="group.status === 'active'" class="mt-5 grid gap-3 sm:grid-cols-2"><button type="button" class="secondary-button" @click="editing = true">Bearbeiten</button><button ref="deleteTrigger" type="button" class="danger-button" @click="askDelete">Ausgabe löschen</button></div><p v-else class="card mt-5 p-4">Diese archivierte Gruppe ist schreibgeschützt.</p></template><dialog ref="dialog" class="delete-dialog rounded-2xl p-0" aria-labelledby="expense-delete-title" @cancel.prevent="cancelDelete"><div class="p-5"><h2 id="expense-delete-title" class="text-xl font-semibold">Ausgabe löschen</h2><p class="mt-3">Ausgabe „{{ expense.description }}“ endgültig löschen?</p><div class="mt-5 flex gap-2"><button type="button" class="secondary-button" @click="cancelDelete">Abbrechen</button><button ref="deleteButton" type="button" class="danger-button" @click="confirmDelete">Endgültig löschen</button></div></div></dialog></div><div v-else class="page-content"><h1 class="text-3xl font-semibold">Ausgabe nicht gefunden</h1><NuxtLink :to="`/groups/${groupId}`" class="secondary-link mt-5">Zur Gruppe</NuxtLink></div></main></template>
